Update patch set 1
Patch Set 1:

Error: Package: python2-networking-bagpipe-10.0.0-0.1.0rc1.el7.noarch (temp)
2019-03-26 04:13:19.510483 | rdo-centos-7 |            Requires: python2-networking-sfc >= 8.0.0

need to wait for networking-sfc build

Patch-set: 1